"""ok

Revision ID: 779b77e2f98d
Revises: 5407c06d54d9
Create Date: 2025-04-12 09:27:25.458471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779b77e2f98d'
down_revision: Union[str, None] = '5407c06d54d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('dialogs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('dialogs', 'created')
    op.drop_column('dialogs', 'updated')
    op.add_column('queue_users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('queue_users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('queue_users', 'created')
    op.drop_column('queue_users', 'updated')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'created')
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('queue_users', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('queue_users', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('queue_users', 'updated_at')
    op.drop_column('queue_users', 'created_at')
    op.add_column('dialogs', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('dialogs', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('dialogs', 'updated_at')
    op.drop_column('dialogs', 'created_at')
    # ### end Alembic commands ###
