"""initial

Revision ID: a327e6e68f6c
Revises: 
Create Date: 2025-04-04 04:39:05.234868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a327e6e68f6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('dialog_partner_id', sa.BigInteger(), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('friends', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_users')
    op.drop_table('users')
    # ### end Alembic commands ###
